# Window Configuration
# WINDOW_TITLE: The exact title of the scrcpy window (visible at the top of the window)
# To find it: Look at your scrcpy window's title bar, it usually shows your device model
WINDOW_TITLE = "V2352GA"
WINDOW_WIDTH = 300 * 1.2
WINDOW_HEIGHT = 650 * 1.2

# Detection Thresholds
MATCH_THRESHOLD = 0.98
RED_ICON_THRESHOLD = 0.94
NEW_LEVEL_RED_ICON_THRESHOLD = 0.95
RED_ICON_MIN_MATCHES = 2
NEW_LEVEL_RED_ICON_MIN_MATCHES = 1
RED_ICON_COLOR_CHECK = True
RED_ICON_COLOR_MIN_RATIO = 1.15
RED_ICON_COLOR_MIN_MEAN = 35
RED_ICON_COLOR_SAMPLE_SIZE = 12
RED_ICON_VERIFY_PADDING = 24
RED_ICON_VERIFY_TOLERANCE = 12
RED_ICON_REFINE_RADIUS = 18
RED_ICON_REFINE_THRESHOLD_DROP = 0.02
STATS_RED_ICON_THRESHOLD = 0.97
SEARCH_INTERVAL = 0.35
CLICK_DELAY = 0.05
MOUSE_MOVE_DELAY = 0.004
MOUSE_DOWN_UP_DELAY = 0.004
DOUBLE_CLICK_DELAY = 0.02
MIN_CLICK_INTERVAL = 0.005
MOUSE_POSITION_TOLERANCE = 2
MOUSE_MOVE_RETRIES = 3
MOUSE_MOVE_RETRY_DELAY = 0.002
MOUSE_TARGET_SETTLE_DELAY = 0.001
MOUSE_TARGET_TIMEOUT = 0.04
MOUSE_TARGET_CHECK_INTERVAL = 0.001
MOUSE_TARGET_HOVER_DELAY = 0.001
MOUSE_STABILIZE_DURATION = 0.004
MOUSE_TARGET_RETRIES = 2
MOUSE_TARGET_CORRECTION_DELAY = 0.001

# Directory Paths
TEMPLATES_DIR = "templates"
ASSETS_DIR = "Assets"
LOGS_DIR = "logs"
SCREENSHOTS_DIR = "screenshots"

# Debug and Visualization Settings
DEBUG = True
SAVE_SCREENSHOTS = True

# ShowForbiddenArea: Enables a visual overlay showing forbidden zones in red
# When True, displays red rectangles over areas where the bot won't click
# Useful for debugging and visualizing the forbidden zones configuration
ShowForbiddenArea = False

# Telegram Bot Configuration
# TELEGRAM_ENABLED: Master switch to enable/disable all Telegram notifications
# Set to True if you want to receive any Telegrazm messages from the bot
TELEGRAM_ENABLED = False

# TELEGRAM_BOT_TOKEN: Your Telegram bot API token from @BotFather
# To get one: Message @BotFather on Telegram, use /newbot command
TELEGRAM_BOT_TOKEN = ""

# TELEGRAM_CHAT_ID: Your Telegram chat ID to receive messages
# To get it: Message your bot, then visit: https://api.telegram.org/bot<YOUR_TOKEN>/getUpdates
# Look for "chat":{"id": YOUR_CHAT_ID in the response
TELEGRAM_CHAT_ID = ""

# Game Element Detection
MAX_SEARCH_Y = 660
EXTENDED_SEARCH_Y = 710

# Click Positions (relative to window)
UPGRADE_POS = (320, 726)
NEW_LEVEL_POS = (40, 700)
REDICON_CHECK_POS = (60, 704)
LEVEL_TRANSITION_POS = (183, 561)
IDLE_CLICK_POS = (2, 390)
INIT_CLICK_POS = (180, 472)
STATS_UPGRADE_POS = (270, 304)
STATS_UPGRADE_BUTTON_POS = (310, 698)
SCROLL_START_POS = (170, 410)
SCROLL_END_POS = (170, 160)
NEW_LEVEL_BUTTON_POS = (30, 692)

# Template Matching Settings
UPGRADE_STATION_THRESHOLD = 0.94
UPGRADE_STATION_COLOR_CHECK = False
BOX_THRESHOLD = 0.97
UNLOCK_THRESHOLD = 0.9
NEW_LEVEL_THRESHOLD = 0.98

# Bot Behavior Configuration
RED_ICON_CYCLE_COUNT = 3
STATS_UPGRADE_CLICK_DURATION = 2
STATS_UPGRADE_CLICK_DELAY = 0.005
STATS_ICON_PADDING = 20
CAPTURE_CACHE_TTL = 0.03
NEW_LEVEL_RED_ICON_CACHE_TTL = 0.03
UPGRADE_HOLD_DURATION = 3.0
UPGRADE_CLICK_INTERVAL = 0.008
SCROLL_UP_CYCLES = 2
NEW_LEVEL_INTERRUPT_INTERVAL = 0.05
NEW_LEVEL_MONITOR_INTERVAL = 0.02
NEW_LEVEL_OVERRIDE_COOLDOWN = 0.25
NO_ICON_SCROLL_UP_COUNT = 3
NO_ICON_SCROLL_DOWN_COUNT = 3

# Red Icon Detection Offsets
RED_ICON_OFFSET_X = 20
RED_ICON_OFFSET_Y = 20

# Red Icon Detection Zones
NEW_LEVEL_RED_ICON_X_MIN = 40
NEW_LEVEL_RED_ICON_X_MAX = 60
NEW_LEVEL_RED_ICON_Y_MIN = 665
NEW_LEVEL_RED_ICON_Y_MAX = 680

UPGRADE_RED_ICON_X_MIN = 280
UPGRADE_RED_ICON_X_MAX = 310
UPGRADE_RED_ICON_Y_MIN = 665
UPGRADE_RED_ICON_Y_MAX = 680

# State Machine Settings
STATE_DELAY = 0.01
MAX_SCROLL_CYCLES = 2
MAIN_LOOP_DELAY = 0.01
SCROLL_DURATION = 0.26
NO_ICON_SCROLL_DURATION = 0.34
SCROLL_STEP_COUNT = 24
SCROLL_MIN_INTERVAL = 0.02
SCROLL_SETTLE_DELAY = 0.01
UPGRADE_SEARCH_INTERVAL = 0.04
UPGRADE_CHECK_INTERVAL = 0.08
IDLE_CLICK_SETTLE_DELAY = 0.015
NEW_LEVEL_BUTTON_DELAY = 0.06
NEW_LEVEL_FOLLOWUP_DELAY = 0.04
TRANSITION_POST_CLICK_DELAY = 0.6
TRANSITION_RETRY_DELAY = 0.1
UNLOCK_POST_CLICK_DELAY = 0.25
WAIT_UNLOCK_RETRY_DELAY = 0.15
FORBIDDEN_ICON_MAX_SCROLLS = 3
FORBIDDEN_ICON_SCROLL_DURATION = 0.2
FORBIDDEN_ICON_SCROLL_COOLDOWN = 0.02
ADAPTIVE_TUNER_ENABLED = True
ADAPTIVE_TUNER_ALPHA = 0.2
ADAPTIVE_TUNER_MIN_CLICK_DELAY = 0.04
ADAPTIVE_TUNER_MAX_CLICK_DELAY = 0.14
ADAPTIVE_TUNER_MIN_MOVE_DELAY = 0.003
ADAPTIVE_TUNER_MAX_MOVE_DELAY = 0.012
ADAPTIVE_TUNER_MIN_UPGRADE_INTERVAL = 0.006
ADAPTIVE_TUNER_MAX_UPGRADE_INTERVAL = 0.012
ADAPTIVE_TUNER_MIN_SEARCH_INTERVAL = 0.03
ADAPTIVE_TUNER_MAX_SEARCH_INTERVAL = 0.08
UPGRADE_STATION_REFINE_RADIUS = 28
UPGRADE_STATION_CLICK_REFINE_RADIUS = 18
AI_VISION_ENABLED = True
AI_VISION_ALPHA = 0.2
AI_VISION_ALPHA_MAX = 0.45
AI_VISION_CONFIDENCE_BOOST = 0.3
AI_RED_ICON_THRESHOLD_MIN = 0.92
AI_RED_ICON_THRESHOLD_MAX = 0.985
AI_RED_ICON_MARGIN = 0.01
AI_RED_ICON_MISS_WINDOW = 2
AI_RED_ICON_MISS_STEP = 0.006
AI_NEW_LEVEL_THRESHOLD_MIN = 0.965
AI_NEW_LEVEL_THRESHOLD_MAX = 0.995
AI_NEW_LEVEL_MISS_WINDOW = 2
AI_NEW_LEVEL_MISS_STEP = 0.004
AI_NEW_LEVEL_RED_ICON_THRESHOLD_MIN = 0.92
AI_NEW_LEVEL_RED_ICON_THRESHOLD_MAX = 0.99
AI_NEW_LEVEL_RED_ICON_MISS_WINDOW = 2
AI_NEW_LEVEL_RED_ICON_MISS_STEP = 0.005
AI_UPGRADE_STATION_THRESHOLD_MIN = 0.9
AI_UPGRADE_STATION_THRESHOLD_MAX = 0.99
AI_UPGRADE_STATION_MISS_WINDOW = 2
AI_UPGRADE_STATION_MISS_STEP = 0.005
AI_STATS_UPGRADE_THRESHOLD_MIN = 0.9
AI_STATS_UPGRADE_THRESHOLD_MAX = 0.99
AI_STATS_UPGRADE_MISS_WINDOW = 2
AI_STATS_UPGRADE_MISS_STEP = 0.005
AI_VISION_STATE_FILE = f"{LOGS_DIR}/vision_state.json"
AI_VISION_SAVE_INTERVAL = 1.0

# Forbidden Zones Configuration
# These zones prevent the bot from clicking on critical UI elements
# Each zone is defined by: X_MIN, X_MAX, Y_MIN, Y_MAX coordinates
# You can add more zones by following the same pattern (FORBIDDEN_ZONE_7, etc.)

# General forbidden click area (botom bar)
FORBIDDEN_CLICK_X_MIN = 60
FORBIDDEN_CLICK_X_MAX = 280
FORBIDDEN_CLICK_Y_MIN = 668

# Zone 1: Right side menu area
FORBIDDEN_ZONE_1_X_MIN = 290
FORBIDDEN_ZONE_1_X_MAX = 350
FORBIDDEN_ZONE_1_Y_MIN = 93
FORBIDDEN_ZONE_1_Y_MAX = 270

# Zone 2: Left side top menu area
FORBIDDEN_ZONE_2_X_MIN = 0
FORBIDDEN_ZONE_2_X_MAX = 60
FORBIDDEN_ZONE_2_Y_MIN = 50
FORBIDDEN_ZONE_2_Y_MAX = 280

# Zone 3: Left side bottom menu area
FORBIDDEN_ZONE_3_X_MIN = 0
FORBIDDEN_ZONE_3_X_MAX = 60
FORBIDDEN_ZONE_3_Y_MIN = 590
FORBIDDEN_ZONE_3_Y_MAX = 667

# Zone 4: Top center notification area
FORBIDDEN_ZONE_4_X_MIN = 145
FORBIDDEN_ZONE_4_X_MAX = 200
FORBIDDEN_ZONE_4_Y_MIN = 65
FORBIDDEN_ZONE_4_Y_MAX = 110

# Zone 5: Bottom navigation bar
FORBIDDEN_ZONE_5_X_MIN = 55
FORBIDDEN_ZONE_5_X_MAX = 285
FORBIDDEN_ZONE_5_Y_MIN = 660
FORBIDDEN_ZONE_5_Y_MAX = 725

# Zone 6: Top bar area
FORBIDDEN_ZONE_6_X_MIN = 0
FORBIDDEN_ZONE_6_X_MAX = 360
FORBIDDEN_ZONE_6_Y_MIN = 0
FORBIDDEN_ZONE_6_Y_MAX = 70
